stages:
  - backend-characterUpdater-build
  - backend-serverless
  - frontend

backend-characterUpdater-build:
  image: golang
  stage: backend-characterUpdater-build
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends zip
    - cd backend/characterUpdater
  script:
    - make package

backend-serverless:
  image: node:11
  stage: backend-serverless
  dependencies:
    - backend-characterUpdater-build
  before_script:
    - cd backend
    - npm install
  script:
    - node_modules/.bin/serverless deploy

frontend-build-sde:
  image: node:11
  stage: frontend
  dependencies:
    - backend-serverless
    - cd frontend
    - yarn
  script:
    - yarn build-sde