stages:
  - backend
  - frontend

backend-characterUpdater-build:
  image: golang
  stage: backend
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends zip
    - cd backend/characterUpdater
  script:
    - make package
  artifacts:
    untracked: true

backend-serverless:
  image: python:3.6
  stage: backend
  dependencies:
    - backend-characterUpdater-build
  before_script:
    - git clone https://github.com/nodesource/distributions.git
    - chmod +x distributions/deb/setup_10.x
    - ./distributions/deb/setup_10.x
    - apt-get install -y nodejs
    - cd backend
    - npm install
  script:
    - node_modules/.bin/serverless deploy

frontend-build-sde:
  image: node:11
  stage: frontend
  dependencies:
    - backend-serverless
  before_script:
    - cd frontend
    - yarn
  script:
    - yarn build-sde