stages:
  - backend-characterUpdater-build
  - backend-serverless
  - frontend
  - deploy

backend-characterUpdater-build:
  stage: backend-characterUpdater-build
  image: golang
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends zip
    - cd backend/characterUpdater
  script:
    - make package
  artifacts:
    expire_in: 1 day
    untracked: true

backend-serverless:
  stage: backend-serverless
  image: python:3.6
  dependencies:
    - backend-characterUpdater-build
  before_script:
    - git clone https://github.com/nodesource/distributions.git
    - chmod +x distributions/deb/setup_10.x
    - ./distributions/deb/setup_10.x
    - apt-get install -y nodejs
    - cd backend
    - npm install
    - mkdir .build
  script:
    - node_modules/.bin/serverless deploy
  artifacts:
    expire_in: 1 day
    paths:
      - backend/.build/

frontend-build:
  stage: frontend
  image: node:11
  dependencies:
    - backend-serverless
  before_script:
    - apt-get update && apt-get install -y jq
    - cd client
    - yarn
    - cat ../backend/.build/stack.json | jq '.ServiceEndpoint'
  script:
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - client/build

frontend-deploy-prod:
  stage: deploy
  image: python3.6
  before_script:
    - pip install awscli
    - cd client
  script:
    - aws s3 sync build s3://evept.err.wtf --acl public-read
  environment:
    name: prod
    url: http://evept.err.wtf
  only:
    - master