---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "12"

inputs:
- name: evept-source-client

params:
  CI: "true"

run:
  path: ls
  args:
  - node_modules
  dir: evept-source-client/client