---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "12"

inputs:
- name: evept-source-client

outputs:
- name: evept-source-client

params:
  CI: "true"

run:
  path: yarn
  args:
  - ((command))
  dir: evept-source-client/client