---
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: evept-queue
spec:
  version: "5.0-v1"
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    storageClassName: do-block-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    terminationPolicy: Pause
    updateStrategy:
      type: RollingUpdate