---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolodex
  labels:
    app: rolodex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolodex
  template:
    metadata:
      labels:
        app: rolodex
    spec:
      containers:
      - name: rolodex
        image: evept/rolodex:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: EVEPT_AUTH0_DOMAIN
          value: evept-dev.eu.auth0.com
        - name: EVEPT_AUTH0_API_IDENTIFIER
          value: https://api.evept-dev.err.wtf/
        ports:
        - name: http
          containerPort: 8500
      initContainers:
      - name: migrations
        image: migrate/migrate
        volumeMounts:
        - name: evept-db-creds
          mountPath: "/etc/evept/db"
          readOnly: true
        - name: github-token
          mountPath: "/etc/evept/github"
          readOnly: true
        command:
        - "migrate"
        - "-source github://`cat /etc/evept/github/user`:`cat /etc/evept/github/token`@hreeder/evept/dbmigrations/rolodex#dev"
        - "-database postgres://`cat /etc/evept/db/POSTGRES_USER`:`cat /etc/evept/db/POSTGRES_PASSWORD`@evept-db:5432/evept?sslmode=disable&x-migrations-table=migrations_rolodex"
        - "up"
      volumes:
      - name: evept-db-creds
        secret:
          secretName: evept-db-auth
      - name: github-token
        secret:
          secretName: github-token
...
---
apiVersion: v1
kind: Service
metadata:
  name: rolodex
  labels:
    app: rolodex
spec:
  selector:
    app: rolodex
  ports:
  - name: http
    port: 8500
    targetPort: http
