---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rolodex
  namespace: evept
  labels:
    app: rolodex
data:
  EVEPT_AUTH0_API_IDENTIFIER: https://api.evept-dev.err.wtf/
  EVEPT_AUTH0_DOMAIN: evept-dev.eu.auth0.com
  EVEPT_QUEUE_HOST: evept-queue
  EVEPT_DB_HOST: evept-db
  EVEPT_DB_NAME: evept
  EVEPT_ALLOWED_CORS_ORIGINS: https://evept-dev.err.wtf
  EVEPT_DEBUG: "true"
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolodex
  namespace: evept
  labels:
    app: rolodex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolodex
  template:
    metadata:
      labels:
        app: rolodex
    spec:
      containers:
      - name: rolodex
        image: evept/rolodex:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: rolodex
        ports:
        - name: http
          containerPort: 8500
        volumeMounts:
        - name: evept-db-creds
          mountPath: /etc/evept/db/credentials
        - name: evept-esi
          mountPath: /etc/evept/esi
      initContainers:
      - name: migrations
        image: migrate/migrate
        envFrom:
        - secretRef:
            name: evept-db-auth
        - secretRef:
            name: github-token
        command: ["/migrate"]
        args:
        - "-source"
        - "github://$(user):$(token)@hreeder/evept/dbmigrations/rolodex#dev"
        - "-database"
        - "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@evept-db:5432/evept?sslmode=disable&x-migrations-table=migrations_rolodex"
        - "up"
      volumes:
      - name: evept-db-creds
        secret:
          secretName: evept-db-auth
      - name: evept-esi
        secret:
          secretName: esi-credentials-dev
...
---
apiVersion: v1
kind: Service
metadata:
  name: rolodex
  namespace: evept
  labels:
    app: rolodex
spec:
  selector:
    app: rolodex
  ports:
  - name: http
    port: 8500
    targetPort: http
