---
resource_types:
- name: kube
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"

resources:
- name: evept-source
  type: git
  icon: github-circle
  source:
    uri: https://github.com/hreeder/evept.git
    branch: dev

- name: evept-source-rolodex
  type: git
  icon: github-circle
  source:
    uri: https://github.com/hreeder/evept.git
    branch: dev
    paths:
    - services/rolodex/*
    - pkg/rolodex/*
    - pkg/shared/*
    - pkg/util/*

- name: evept-source-scripts
  type: git
  icon: github-circle
  source:
    uri: https://github.com/hreeder/evept.git
    branch: dev
    paths:
    - scripts/*

- name: oneoffscripts-image
  type: docker-image
  icon: docker
  source:
    repository: evept/oneoffscripts
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: rolodex-image
  type: docker-image
  icon: docker
  source:
    repository: evept/rolodex
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: kube
  type: kube
  source:
    certificate_authority: ((kube.cluster_ca))
    server: ((kube.cluster_url))
    token: ((kube.token))
    namespace: evept

groups:
- name: support
  jobs:
  - build-push-oneoff
  - seed-eve-sde
- name: services
  jobs:
  - build-push-rolodex
#   - deploy-rolodex

jobs:
- name: build-push-oneoff
  plan:
  - get: evept-source-scripts
    trigger: true
  - put: oneoffscripts-image
    params:
      build: evept-source-scripts/scripts

- name: seed-eve-sde
  plan:
  - get: evept-source
  - put: kube
    params:
      kubectl: create -f evept-source/kubernetes/jobs/seed-sde.yaml
      wait_until_ready_selector: job=seed-eve-sde

- name: build-push-rolodex
  plan:
  - get: evept-source-rolodex
    trigger: true
  - put: rolodex-image
    params:
      build: evept-source-rolodex
      dockerfile: dockerfiles/rolodex.Dockerfile

# - name: deploy-rolodex