---
resource_types:
- name: kube
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"

resources:
- name: evept-source
  type: git
  icon: github-circle
  source:
    uri: https://github.com/hreeder/evept.git
    branch: dev

- name: oneoffscripts-image
  type: docker-image
  icon: docker
  source:
    repository: evept/oneoffscripts
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: kube
  type: kube
  source:
    certificate_authority: ((kube.cluster_ca))
    server: ((kube.cluster_url))
    token: ((kube.token))

groups:
- name: support
  jobs:
  - build-push-oneoff
  - seed-eve-sde

jobs:
- name: build-push-oneoff
  plan:
  - get: evept-source
    trigger: true
  - put: oneoffscripts-image
    params:
      build: evept-source/scripts

- name: seed-eve-sde
  plan:
  - get: evept-source
  - put: kube
    params:
      kubectl: apply -f evept-source/kubernetes/jobs/seed-sde.yaml
      wait_until_ready_selector: job=seed-eve-sde